### ISSUE TITLE
Unable to compile with CUDA 11.0

### ISSUE THREAD

**Issue by freewym** [k2-fsa/k2#582]
`make -j _k2` has the following error:

/usr/local/cuda-11.0/bin/../targets/x86_64-linux/include/thrust/system/cuda/config.h:78:2: error: #error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.

Maybe can be solved by adding some "if else" to conditionally download CUB according to CUDA version in k2?

**Comment by csukuangfj** [comment]
Thanks for reporting. Will try to fix it.
