### ISSUE TITLE
Error at compilation: random.h(104): expected a declaration

### ISSUE THREAD

**Issue by lumaku** [k2-fsa/k2#972]
I get this error when building k2:

```text
/usr/include/c++/12.1.0/bits/random.h(104): error: expected a declaration
```

It happens during the compilation of `algorithms.cu`. Following the line in the error message, it happens to be a macro for `int`:

```C++
#if __SIZEOF_INT128__ > __SIZEOF_LONG_LONG__
    template<int __s>
      struct _Select_uint_least_t<__s, 1>
      { __extension__ using type = unsigned __int128; };
#endif
```

As `algorithms.cu` hasn't changed in recent months, this may be an issue with a newer C++ compiler version (here, GNU CXX 12.1.0). I am not sure about how to solve this.... Here is the full output:

```text
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.10
creating build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/utils.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/torch_version.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/symbol_table.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/rnnt_loss.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/rnnt_decode.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/ops.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/nbest.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/mutual_information.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/fsa_properties.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/fsa_algo.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/fsa.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/dense_fsa_vec.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/ctc_loss.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/autograd_utils.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/autograd.py -> build/lib.linux-x86_64-3.10/k2
copying k2/python/k2/__init__.py -> build/lib.linux-x86_64-3.10/k2
creating build/lib.linux-x86_64-3.10/k2/ragged
copying k2/python/k2/ragged/__init__.py -> build/lib.linux-x86_64-3.10/k2/ragged
creating build/lib.linux-x86_64-3.10/k2/sparse
copying k2/python/k2/sparse/autograd.py -> build/lib.linux-x86_64-3.10/k2/sparse
copying k2/python/k2/sparse/__init__.py -> build/lib.linux-x86_64-3.10/k2/sparse
creating build/lib.linux-x86_64-3.10/k2/version
copying k2/python/k2/version/version.py -> build/lib.linux-x86_64-3.10/k2/version
copying k2/python/k2/version/__main__.py -> build/lib.linux-x86_64-3.10/k2/version
copying k2/python/k2/version/__init__.py -> build/lib.linux-x86_64-3.10/k2/version
running build_ext
Setting PYTHON_EXECUTABLE to /usr/bin/python
build command is:

                cd build/temp.linux-x86_64-3.10

                cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python /tmp/trizen-louis/python-k2-git/src/python-k2-git

                cat k2/csrc/version.h

                make  _k2
            
-- Enabled languages: CXX;CUDA
-- The CXX compiler identification is GNU 12.1.0
-- The CUDA compiler identification is NVIDIA 11.6.124
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /opt/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- K2_OS: Arch Linux
-- Found Git: /usr/bin/git (found version "2.36.1") 
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Looking for C++ include execinfo.h
-- Looking for C++ include execinfo.h - found
-- Performing Test K2_COMPILER_SUPPORTS_CXX14
-- Performing Test K2_COMPILER_SUPPORTS_CXX14 - Success
-- C++ Standard version: 14
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.5;5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.6+PTX
-- K2_COMPUTE_ARCH_FLAGS: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
-- K2_COMPUTE_ARCH_CANDIDATES 35;50;60;61;70;75;80;86
-- Adding arch 35
-- Adding arch 50
-- Adding arch 60
-- Adding arch 61
-- Adding arch 70
-- Adding arch 75
-- Adding arch 80
-- Adding arch 86
-- K2_COMPUTE_ARCHS: 35;50;60;61;70;75;80;86
-- Could NOT find Valgrind (missing: Valgrind_INCLUDE_DIR Valgrind_EXECUTABLE) 
-- Downloading pybind11
-- pybind11 is downloaded to /tmp/trizen-louis/python-k2-git/src/python-k2-git/build/temp.linux-x86_64-3.10/_deps/pybind11-src
-- pybind11 v2.6.0 
CMake Warning (dev) at /usr/share/cmake/Modules/CMakeDependentOption.cmake:89 (message):
  Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
  Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  build/temp.linux-x86_64-3.10/_deps/pybind11-src/CMakeLists.txt:91 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python (found version "3.10.4") 
-- Found PythonLibs: /usr/lib/libpython3.10.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Python executable: /usr/bin/python
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Found glog with new-style glog target.
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.20.1
-- Found CUDA: /opt/cuda (found version "11.6") 
-- Caffe2: CUDA detected: 11.6
-- Caffe2: CUDA nvcc is: /opt/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /opt/cuda
-- Caffe2: Header version is: 11.6
-- Found CUDNN: /usr/lib/libcudnn.so  
-- Found cuDNN: v8.4.0  (include: /usr/lib/python3.10/site-packages/torch/include, library: /usr/lib/libcudnn.so)
-- /opt/cuda/lib64/libnvrtc.so shorthash is 4dd39364
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.5;5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.6+PTX
-- Added CUDA NVCC flags for: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
CMake Warning at /usr/lib64/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /usr/lib64/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  cmake/torch.cmake:11 (find_package)
  CMakeLists.txt:266 (include)


-- Found Torch: /usr/lib/python3.10/site-packages/torch/lib/libtorch.so  
-- PyTorch version: 1.11.0
-- PyTorch cuda version: 11.6
-- Generated /tmp/trizen-louis/python-k2-git/src/python-k2-git/k2/python/k2/torch_version.py
-- Downloading moderngpu
-- moderngpu is downloaded to /tmp/trizen-louis/python-k2-git/src/python-k2-git/build/temp.linux-x86_64-3.10/_deps/moderngpu-src
-- Downloading googletest
-- googletest is downloaded to /tmp/trizen-louis/python-k2-git/src/python-k2-git/build/temp.linux-x86_64-3.10/_deps/googletest-src
-- googletest's binary dir is /tmp/trizen-louis/python-k2-git/src/python-k2-git/build/temp.linux-x86_64-3.10/_deps/googletest-build
CMake Deprecation Warning at build/temp.linux-x86_64-3.10/_deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Deprecation Warning at build/temp.linux-x86_64-3.10/_deps/googletest-src/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at build/temp.linux-x86_64-3.10/_deps/googletest-src/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- CMAKE_CUDA_FLAGS:  -Wno-deprecated-gpu-targets  --expt-extended-lambda -gencode arch=compute_35,code=sm_35 --expt-extended-lambda -gencode arch=compute_50,code=sm_50 --expt-extended-lambda -gencode arch=compute_60,code=sm_60 --expt-extended-lambda -gencode arch=compute_61,code=sm_61 --expt-extended-lambda -gencode arch=compute_70,code=sm_70 --expt-extended-lambda -gencode arch=compute_75,code=sm_75 --expt-extended-lambda -gencode arch=compute_80,code=sm_80 --expt-extended-lambda -gencode arch=compute_86,code=sm_86 -DONNX_NAMESPACE=onnx_c2 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --expt-relaxed-constexpr --expt-extended-lambda -D_GLIBCXX_USE_CXX11_ABI=1 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas 
-- CMAKE_CXX_FLAGS: -march=native -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS         -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -D_GLIBCXX_USE_CXX11_ABI=1 -Wno-unused-variable  -Wno-strict-overflow 
-- CMAKE_CUDA_FLAGS:  -Wno-deprecated-gpu-targets  --expt-extended-lambda -gencode arch=compute_35,code=sm_35 --expt-extended-lambda -gencode arch=compute_50,code=sm_50 --expt-extended-lambda -gencode arch=compute_60,code=sm_60 --expt-extended-lambda -gencode arch=compute_61,code=sm_61 --expt-extended-lambda -gencode arch=compute_70,code=sm_70 --expt-extended-lambda -gencode arch=compute_75,code=sm_75 --expt-extended-lambda -gencode arch=compute_80,code=sm_80 --expt-extended-lambda -gencode arch=compute_86,code=sm_86 -DONNX_NAMESPACE=onnx_c2 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --expt-relaxed-constexpr --expt-extended-lambda -D_GLIBCXX_USE_CXX11_ABI=1 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas 
-- Generated /tmp/trizen-louis/python-k2-git/src/python-k2-git/build/temp.linux-x86_64-3.10/k2/csrc/version.h
-- PYTHON_LIBRARIES: /usr/lib/libpython3.10.so
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/trizen-louis/python-k2-git/src/python-k2-git/build/temp.linux-x86_64-3.10
/**
 * @brief
 * This file contains information for building k2, which is helpful
 * for describing the environment in which k2 is used when creating
 * an issue on GitHub.
 *
 * @copyright
 * Copyright (c)  2020  Mobvoi Inc.        (authors: Fangjun Kuang)
 *
 * @copyright
 * See LICENSE for clarification regarding multiple authors
 *
 * @caution
 * This file is auto-generated by CMake. Do NOT edit!
 * You can find it at build_dir/k2/csrc/version.h
 */

#ifndef K2_CSRC_VERSION_H_
#define K2_CSRC_VERSION_H_

namespace k2 {

// Version of k2 in "major.minor.patch" format
static constexpr const char *kVersion = "1.15.1";

// The commit used to build k2
static constexpr const char *kGitSha1 = "ecfe7bd6d9189964bf3ff043038918d889a43185";

// Date of the commit used to build k2
static constexpr const char *kGitDate = "Tue May 10 04:57:55 2022";

// Version of CUDA used to build k2.
// Its format is "major.minor", e.g., 10.1
static constexpr const char *kCudaVersion = "11.6";

// cuDNN version, e.g., 8.0.2
static constexpr const char *kCudnnVersion = "8.4.0";

// clang-format off
// Version of Python used to build k2 Python bindings.
static constexpr const char *kPythonVersion = "3.10";

// clang-format on

// CMake build type, e.g., Release or Debug.
static constexpr const char *kBuildType = "Release";

// The operating system that is used to build k2, e.g., Ubuntu 16.04 LTS
static constexpr const char *kOS = R"os(Arch Linux)os";

// e.g., 3.18.0
static constexpr const char *kCMakeVersion = "3.23.1";

// Version of the compiler, e.g., 5.4.0
static constexpr const char *kGCCVersion = "12.1.0";

// CUDA flags used to compile k2
static constexpr const char *kCMakeCudaFlags = R"cuda_flags( -Wno-deprecated-gpu-targets  --expt-extended-lambda -gencode arch=compute_35,code=sm_35 --expt-extended-lambda -gencode arch=compute_50,code=sm_50 --expt-extended-lambda -gencode arch=compute_60,code=sm_60 --expt-extended-lambda -gencode arch=compute_61,code=sm_61 --expt-extended-lambda -gencode arch=compute_70,code=sm_70 --expt-extended-lambda -gencode arch=compute_75,code=sm_75 --expt-extended-lambda -gencode arch=compute_80,code=sm_80 --expt-extended-lambda -gencode arch=compute_86,code=sm_86 -DONNX_NAMESPACE=onnx_c2 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --expt-relaxed-constexpr --expt-extended-lambda -D_GLIBCXX_USE_CXX11_ABI=1 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas )cuda_flags";

// CXX flags used to compile k2
static constexpr const char *kCMakeCxxFlags = R"cxx_flags(-march=native -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS         -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -D_GLIBCXX_USE_CXX11_ABI=1 -Wno-unused-variable  -Wno-strict-overflow )cxx_flags";

// Which PyTorch version k2 is using, e.g., 1.6.0+cu101
static constexpr const char *kTorchVersion = "1.11.0";

// Which CUDA version PyTorch is using, e.g., 10.1
static constexpr const char *kTorchCudaVersion = "11.6";

#ifndef K2_WITH_CUDA
#define K2_WITH_CUDA
#endif

#ifdef K2_WITH_CUDA
  static constexpr bool kWithCuda = true;
#else
  static constexpr bool kWithCuda = false;
#endif

// Indicate whether NVTX is enabled or not
#ifndef K2_ENABLE_NVTX
#define K2_ENABLE_NVTX
#endif

#ifdef K2_ENABLE_NVTX
static constexpr bool kEnableNvtx = true;
#else
static constexpr bool kEnableNvtx = false;
#endif
}  // namespace k2

#endif  //  K2_CSRC_VERSION_H_
[  3%] Building CUDA object k2/csrc/CMakeFiles/k2_log.dir/log.cu.o
[  3%] Linking CUDA shared library ../../lib/libk2_log.so
[  3%] Built target k2_log
[  6%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/aux_labels.cc.o
[  6%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/arcsort.cc.o
[  9%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/connect.cc.o
[  9%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/determinize.cc.o
[  9%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/determinize_pruned.cc.o
[ 12%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa.cc.o
[ 12%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_equivalent.cc.o
[ 15%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_renderer.cc.o
[ 15%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_util.cc.o
[ 18%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/intersect.cc.o
[ 18%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/properties.cc.o
[ 21%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/rmepsilon_pruned.cc.o
[ 21%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/topsort.cc.o
[ 21%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/util.cc.o
[ 24%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/weights.cc.o
[ 24%] Linking CXX shared library ../../../lib/libk2fsa.so
[ 24%] Built target fsa
[ 27%] Building CUDA object k2/csrc/CMakeFiles/context.dir/algorithms.cu.o
[ 27%] Building CUDA object k2/csrc/CMakeFiles/context.dir/array_of_ragged.cu.o
[ 27%] Building CUDA object k2/csrc/CMakeFiles/context.dir/array_ops.cu.o
[ 30%] Building CUDA object k2/csrc/CMakeFiles/context.dir/connect.cu.o
[ 30%] Building CUDA object k2/csrc/CMakeFiles/context.dir/context.cu.o
[ 33%] Building CUDA object k2/csrc/CMakeFiles/context.dir/dtype.cu.o
[ 33%] Building CUDA object k2/csrc/CMakeFiles/context.dir/fsa.cu.o
[ 36%] Building CUDA object k2/csrc/CMakeFiles/context.dir/fsa_algo.cu.o
/usr/include/c++/12.1.0/bits/random.h(104): error: expected a declaration

/usr/include/c++/12.1.0/bits/random.h(104): error: expected a declaration

/usr/include/c++/12.1.0/bits/random.h(104): error: expected a declaration

/usr/include/c++/12.1.0/bits/random.h(104): error: expected a declaration

/usr/include/c++/12.1.0/bits/random.h(104): error: expected a declaration

/usr/include/c++/12.1.0/bits/random.h(104): error: expected a declaration

1 error detected in the compilation of "/tmp/trizen-louis/python-k2-git/src/python-k2-git/k2/csrc/algorithms.cu".
make[3]: *** [k2/csrc/CMakeFiles/context.dir/build.make:76: k2/csrc/CMakeFiles/context.dir/algorithms.cu.o] Fehler 1
make[3]: *** Es wird auf noch nicht beendete Prozesse gewartet....
1 error detected in the compilation of "/tmp/trizen-louis/python-k2-git/src/python-k2-git/k2/csrc/array_of_ragged.cu".
make[3]: *** [k2/csrc/CMakeFiles/context.dir/build.make:90: k2/csrc/CMakeFiles/context.dir/array_of_ragged.cu.o] Fehler 1
1 error detected in the compilation of "/tmp/trizen-louis/python-k2-git/src/python-k2-git/k2/csrc/array_ops.cu".
make[3]: *** [k2/csrc/CMakeFiles/context.dir/build.make:104: k2/csrc/CMakeFiles/context.dir/array_ops.cu.o] Fehler 1
1 error detected in the compilation of "/tmp/trizen-louis/python-k2-git/src/python-k2-git/k2/csrc/connect.cu".
make[3]: *** [k2/csrc/CMakeFiles/context.dir/build.make:118: k2/csrc/CMakeFiles/context.dir/connect.cu.o] Fehler 1
1 error detected in the compilation of "/tmp/trizen-louis/python-k2-git/src/python-k2-git/k2/csrc/fsa.cu".
make[3]: *** [k2/csrc/CMakeFiles/context.dir/build.make:160: k2/csrc/CMakeFiles/context.dir/fsa.cu.o] Fehler 1
1 error detected in the compilation of "/tmp/trizen-louis/python-k2-git/src/python-k2-git/k2/csrc/fsa_algo.cu".
make[3]: *** [k2/csrc/CMakeFiles/context.dir/build.make:174: k2/csrc/CMakeFiles/context.dir/fsa_algo.cu.o] Fehler 1
make[2]: *** [CMakeFiles/Makefile2:563: k2/csrc/CMakeFiles/context.dir/all] Fehler 2
make[1]: *** [CMakeFiles/Makefile2:2081: k2/python/csrc/CMakeFiles/_k2.dir/rule] Fehler 2
make: *** [Makefile:849: _k2] Fehler 2
Traceback (most recent call last):
  File "/tmp/trizen-louis/python-k2-git/src/python-k2-git/setup.py", line 201, in <module>
    setuptools.setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/tmp/trizen-louis/python-k2-git/src/python-k2-git/setup.py", line 146, in build_extension
    raise Exception('Failed to build k2')
Exception: Failed to build k2

**Comment by csukuangfj** [comment]
Are you able to build a CPU version of k2 (you can use `export K2_CMAKE_ARGS="-DK2_WITH_CUDA=OFF"` before running `python3 setup.py build`)?

If so, the issue may be that CUDA 11.6 does not support GCC 12.1.0.

**Comment by lumaku** [comment]
Yes. The build process completes without errors after `export K2_CMAKE_ARGS="-DK2_WITH_CUDA=OFF"`...

**Comment by csukuangfj** [comment]
> Yes. The build process completes without errors after `export K2_CMAKE_ARGS="-DK2_WITH_CUDA=OFF"`...

In that case, I think the issue is from using CUDA 11.6 with GCC 12.1.0.

I am not sure what is the latest version of GCC that is supported by CUDA 11.6.

**Comment by csukuangfj** [comment]
From https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements

![Screen Shot 2022-05-14 at 22 05 07](https://user-images.githubusercontent.com/5284924/168429202-517045f2-2211-4369-a996-74d96c7a91c2.png)

Only GCC 11 is listed in the table. I think GCC 12 is too new and is not supported by CUDA 11.6 or 11.7

Can you switch to GCC 11?

**Comment by lumaku** [comment]
I tried, it did not compile with GCC 11.3.0 and LLVM 13.0...

**Comment by danpovey** [comment]
Perhaps you could show the errors.  We are using 11.1 and 11.2.  The very newest CUDA toolkit may not be quite as easy to set up.

**Comment by lumaku** [comment]
Compilation works again with the most recent k2 version on CUDA 11.7.64, with Clang 14.0.6 as well as with GNU GCC 12.1.0.

The CUDA version on my computer is installed over the system package manager that provides the latest version, but I can't easily downgrade for an investigation of the issue.

As the compilation error does not occur anymore, this issue can be closed. Thanks!
